# Welcome to Jekyll!

# Website settings
title: "Feo y princesa se van de boda"
author: "Feo y princesa"
description: "Este es el comienzo, ven a ver el final"
keywords: "Boda,Feo,Princesa,github,gh-pages"
baseurl: "/"
url: "http://boda.feoyprincesa.es"
# url: "http://127.0.0.1:4000"

feo:
  name: Feo
  real_name: Pablo
  image: static/img/feo.jpg

princesa:
  name: Princesa
  real_name: Bea
  image: static/img/princesa.jpg

# sections
sections:
  - id: 'us'
    name: 'Nosotros'
    tpl: 'us.html'
    css: ''

  - id: 'steps'
    name: 'Organización'
    tpl: 'steps.html'
    css: 'timeline'

  - id: 'news'
    name: 'Noticias'
    tpl: 'news.html'
    css: 'testimonials navy-section'

  - id: 'progress'
    name: 'Progreso'
    tpl: 'progress.html'
    css: 'team'

  - id: 'places'
    name: 'Lugares'
    tpl: 'places.html'
    css: 'project'

  - id: 'contact'
    name: 'Contacto'
    tpl: 'contact.html'
    css: 'contact'

# blog img path
img_path: 'static/img/blog'

#disqus:
#  name: feoyprincesa
#  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# google analytics
#ga:
#  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
